import { useEffect, useState } from "react";
import { ArrowRight, Box, CheckCircle2, Clock3, CircleDot, Eye, FileClock, Layers3, Palette, Plus, Rocket, Sparkles, TrendingUp, Upload, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button, Card, Loading, StatusBadge } from "../components/ui";
import { dashboardService, type DashboardData } from "../services/dashboard/dashboardService";

const icons = { visitors: Users, duration: Clock3, interaction: CircleDot, coverage: Layers3 };
const shortcuts = [{ label: "新建3D资产", caption: "上传景区视频", icon: Upload, to: "/assets/new" }, { label: "新建主题", caption: "创建运营主题", icon: Palette, to: "/themes?create=1" }, { label: "配置互动点", caption: "管理游客热点", icon: CircleDot, to: "/operations/interactions" }, { label: "预览并发布", caption: "检查 Draft 变更", icon: Rocket, to: "/operations/publish" }];

export function DashboardPage() {
  const navigate = useNavigate(); const [data, setData] = useState<DashboardData>();
  useEffect(() => { dashboardService.getDashboard().then(setData); }, []);
  if (!data) return <div className="page"><Loading label="正在汇总景区运营状态"/></div>;
  return <div className="page dashboard-page operations-dashboard">
    <section className="hero-heading"><p>杭州西湖景区 · 数字运营中心</p><h1>运营工作台</h1><span>今天发生了什么、当前要处理什么，一页掌握</span></section>
    <section className="metric-grid">{data.kpis.map((item) => { const Icon=icons[item.kind]; return <Card className="metric-card" key={item.label}><div className="metric-top"><Icon size={20}/><StatusBadge>{item.trend}</StatusBadge></div><strong>{item.value}</strong><span>{item.label}</span></Card>; })}</section>
    <section className="ops-primary-grid"><Card className="runtime-status"><div className="panel-heading"><div><p>当前线上运行状态</p><h2>游客端正在运行什么？</h2></div><span className="live-dot">LIVE</span></div><div className="runtime-theme"><Sparkles/><div><small>线上主题</small><strong>{data.online.theme}</strong><span>Published v{data.online.version}</span></div>{data.online.hasDraft&&<StatusBadge tone="warning">{data.online.draftTheme}等待发布</StatusBadge>}</div><div className="runtime-facts"><div><small>在线 Scene</small><strong>{data.online.onlineScenes}</strong></div><div><small>启用互动点</small><strong>{data.online.enabledInteractions} / {data.online.totalInteractions}</strong></div><div><small>上次发布</small><strong>{new Date(data.online.updatedAt).toLocaleDateString("zh-CN")}</strong></div><div><small>Draft</small><strong className={data.online.hasDraft?"warning-text":""}>{data.online.hasDraft?"有未发布配置":"无"}</strong></div></div><Button className="secondary-button" onClick={()=>navigate(data.online.hasDraft?"/operations/publish":"/themes")}>{data.online.hasDraft?"查看变更":"查看主题配置"}<ArrowRight size={15}/></Button></Card>
      <Card className="todo-center"><div className="panel-heading"><div><p>运营待办</p><h2>现在需要处理什么？</h2></div><FileClock/></div><div className="todo-list">{data.todos.length?data.todos.map((todo)=><div className="todo-item" key={todo.id}><span className={`todo-dot ${todo.tone}`}/><div><strong>{todo.title}</strong><p>{todo.description}</p><StatusBadge tone={todo.tone}>{todo.status}</StatusBadge></div><button onClick={()=>navigate(todo.to)}>{todo.action}<ArrowRight/></button></div>):<div className="all-clear"><CheckCircle2/><strong>当前没有待办</strong><span>所有配置均已处理</span></div>}</div></Card></section>
    <section className="ops-analysis-grid"><Card className="funnel-panel clickable-panel" onClick={()=>navigate("/operations")} role="button"><div className="panel-heading"><div><p>互动运营漏斗 · Demo 模拟</p><h2>数字内容是否带来参与？</h2></div><TrendingUp/></div><div className="funnel-bars">{data.funnel.map((item,index)=><div key={item.label}><span>{item.label}</span><i style={{width:`${item.value/data.funnel[0].value*100}%`}}/><strong>{item.value.toLocaleString()}</strong>{index>0&&<small>{Math.round(item.value/data.funnel[index-1].value*100)}%</small>}</div>)}</div><span className="panel-link">进入互动运营 <ArrowRight/></span></Card>
      <Card className="scene-performance"><div className="panel-heading"><div><p>场景运营表现 · Demo 模拟</p><h2>哪里热门，哪里待提升？</h2></div><Eye/></div><div className="scene-table"><div className="scene-table-head"><span>场景</span><span>游客量</span><span>平均停留</span><span>互动率</span><span>判断</span></div>{data.scenes.map((scene)=><div className="scene-row" key={scene.name}><strong>{scene.name}</strong><span>{scene.visitors}</span><span>{scene.stay}</span><span>{scene.interactionRate}</span><StatusBadge tone={scene.status==="热门"?"success":"warning"}>{scene.status}</StatusBadge></div>)}</div></Card></section>
    <section className="ops-bottom-grid"><Card className="insights-panel"><div className="panel-heading"><div><p>运营洞察 · Demo 模拟建议</p><h2>下一步可以做什么？</h2></div><Sparkles/></div>{data.insights.map((insight)=><div className="insight-item" key={insight.title}><span><Sparkles/></span><div><strong>{insight.title}</strong><p>{insight.description}</p></div><Button className="secondary-button" onClick={()=>navigate(insight.to)}>{insight.action}</Button></div>)}</Card>
      <Card className="asset-health" onClick={()=>navigate("/assets")} role="button"><div className="panel-heading"><div><p>3D 资产健康度</p><h2>空间数字资产库</h2></div><Box/></div><div className="health-grid"><div><i className="health-published"/><strong>{data.assetHealth.published}</strong><span>已上线</span></div><div><i className="health-building"/><strong>{data.assetHealth.reconstructing}</strong><span>AI重建中</span></div><div><i className="health-review"/><strong>{data.assetHealth.pending_review}</strong><span>待审核</span></div><div><i className="health-failed"/><strong>{data.assetHealth.failed}</strong><span>失败</span></div></div><span className="health-link">查看全部资产 <ArrowRight/></span></Card></section>
    <section className="section-block"><div className="section-title"><h2>快捷操作</h2><span>常用运营入口</span></div><div className="desktop-shortcuts">{shortcuts.map(({label,caption,icon:Icon,to})=><button key={label} onClick={()=>navigate(to)}><span><Icon/></span><div><strong>{label}</strong><small>{caption}</small></div><ArrowRight/></button>)}</div></section>
  </div>;
}
