import { useEffect, useState } from "react";
import { AlertTriangle, ArrowRight, Box, CircleDot, Clock3, Eye, Layers3, Palette, Rocket, Sparkles, TrendingUp, Upload, Users, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button, Card, Loading, StatusBadge } from "../components/ui";
import { dashboardService, type DashboardData } from "../services/dashboard/dashboardService";

const icons = { visitors: Users, duration: Clock3, interaction: CircleDot, coverage: Layers3 };
const shortcuts = [{ label: "新建3D资产", caption: "上传景区视频", icon: Upload, to: "/assets/new" }, { label: "新建主题", caption: "创建运营主题", icon: Palette, to: "/themes?create=1" }, { label: "配置互动点", caption: "管理游客热点", icon: CircleDot, to: "/operations/interactions" }, { label: "预览并发布", caption: "检查 Draft 变更", icon: Rocket, to: "/operations/publish" }];
const crowdAreas = [{ name: "入口大厅", value: 32, position: "entrance" }, { name: "核心展厅", value: 87, risk: true, position: "main" }, { name: "数字互动区", value: 68, position: "digital" }, { name: "文创区", value: 45, position: "shop" }, { name: "连廊", value: 73, position: "hall" }, { name: "出口区", value: 28, position: "exit" }];

export function DashboardPage() {
  const navigate = useNavigate(); const [data, setData] = useState<DashboardData>(); const [solutionState, setSolutionState] = useState<"closed" | "thinking" | "ready">("closed");
  useEffect(() => { dashboardService.getDashboard().then(setData); }, []);
  useEffect(() => { if (solutionState !== "thinking") return; const timer = window.setTimeout(() => setSolutionState("ready"), 1800); return () => window.clearTimeout(timer); }, [solutionState]);
  if (!data) return <div className="page"><Loading label="正在汇总景区运营状态"/></div>;
  return <div className="page dashboard-page operations-dashboard">
    <section className="hero-heading"><p>杭州西湖景区 · 数字运营中心</p><h1>运营工作台</h1><span>今天发生了什么、当前要处理什么，一页掌握</span></section>
    <section className="metric-grid">{data.kpis.map(item => { const Icon = icons[item.kind]; return <Card className="metric-card" key={item.label}><div className="metric-top"><Icon size={20}/><StatusBadge>{item.trend}</StatusBadge></div><strong>{item.value}</strong><span>{item.label}</span></Card>; })}</section>
    <section className="ops-primary-grid crowd-primary-grid">
      <Card className="runtime-status compact-runtime"><div className="panel-heading"><div><p>游客端运行状态</p><h2>游客端正在运行什么？</h2></div><span className="live-dot">运行中</span></div><div className="runtime-theme"><Sparkles/><div><small>当前主题</small><strong>{data.online.theme}</strong><span>Published v{data.online.version}</span></div></div><div className="runtime-facts compact"><div><small>在线 Scene</small><strong>{data.online.onlineScenes}</strong></div><div><small>最近发布</small><strong>{new Date(data.online.updatedAt).toLocaleDateString("zh-CN")}</strong></div></div><Button className="secondary-button" onClick={() => navigate("/themes")}>查看配置<ArrowRight size={15}/></Button></Card>
      <Card className="crowd-monitor"><div className="panel-heading"><div><p>运营安全监测 · Mock</p><h2>客流量实时监控</h2></div><span className="crowd-live">实时</span></div><div className="crowd-heatmap"><div className="museum-plan"><i className="plan-room room-a"/><i className="plan-room room-b"/><i className="plan-room room-c"/><i className="plan-room room-d"/><i className="plan-corridor"/><i className="heat heat-cool"/><i className="heat heat-warm"/><i className="heat heat-hot"/>{crowdAreas.map(area => <div key={area.name} className={`heat-label ${area.position}`}><span>{area.name}{area.risk && <AlertTriangle size={12}/>}</span><strong>{area.value}%</strong></div>)}</div></div><div className="crowd-legend"><span><i className="normal"/>正常</span><span><i className="busy"/>较密集</span><span><i className="risk"/>高风险</span></div><div className="crowd-risk-note"><div><AlertTriangle size={17}/><p><strong>博物馆局部区域人群密度过高，易有踩踏风险</strong><small>建议及时进行人流疏导与入口限流。</small></p></div><Button onClick={() => setSolutionState("thinking")}>生成解决方案</Button></div>{solutionState !== "closed" && <div className="crowd-solution-overlay"><section className="crowd-solution" role="dialog" aria-label="客流疏导建议"><button className="modal-close" onClick={() => setSolutionState("closed")}><X/></button>{solutionState === "thinking" ? <div className="crowd-thinking"><i/><p>AI 正在分析区域密度、动线与入口承载量</p><small>正在生成客流疏导建议…</small></div> : <><p>运营安全建议</p><h2>客流疏导建议</h2><ul><li>对核心展厅入口实施临时限流</li><li>引导游客前往低密度区域</li><li>开启备用疏散通道</li><li>安排现场工作人员进行人流疏导</li><li>必要时启动广播提示</li></ul><Button onClick={() => setSolutionState("closed")}>我知道了</Button></>}</section></div>}</Card>
    </section>
    <section className="ops-analysis-grid"><Card className="funnel-panel clickable-panel" onClick={() => navigate("/operations")} role="button"><div className="panel-heading"><div><p>互动运营漏斗 · Demo 模拟</p><h2>数字内容是否带来参与？</h2></div><TrendingUp/></div><div className="funnel-bars">{data.funnel.map((item, index) => <div key={item.label}><span>{item.label}</span><i style={{ width: `${item.value / data.funnel[0].value * 100}%` }}/><strong>{item.value.toLocaleString()}</strong>{index > 0 && <small>{Math.round(item.value / data.funnel[index - 1].value * 100)}%</small>}</div>)}</div><span className="panel-link">进入互动运营 <ArrowRight/></span></Card><Card className="scene-performance"><div className="panel-heading"><div><p>场景运营表现 · Demo 模拟</p><h2>哪里热门，哪里待提升？</h2></div><Eye/></div><div className="scene-table"><div className="scene-table-head"><span>场景</span><span>游客量</span><span>平均停留</span><span>互动率</span><span>判断</span></div>{data.scenes.map(scene => <div className="scene-row" key={scene.name}><strong>{scene.name}</strong><span>{scene.visitors}</span><span>{scene.stay}</span><span>{scene.interactionRate}</span><StatusBadge tone={scene.status === "热门" ? "success" : "warning"}>{scene.status}</StatusBadge></div>)}</div></Card></section>
    <section className="ops-bottom-grid"><Card className="insights-panel"><div className="panel-heading"><div><p>运营洞察 · Demo 模拟建议</p><h2>下一步可以做什么？</h2></div><Sparkles/></div>{data.insights.map(insight => <div className="insight-item" key={insight.title}><span><Sparkles/></span><div><strong>{insight.title}</strong><p>{insight.description}</p></div><Button className="secondary-button" onClick={() => navigate(insight.to)}>{insight.action}</Button></div>)}</Card><Card className="asset-health" onClick={() => navigate("/assets")} role="button"><div className="panel-heading"><div><p>3D 资产健康度</p><h2>空间数字资产库</h2></div><Box/></div><div className="health-grid"><div><i className="health-published"/><strong>{data.assetHealth.published}</strong><span>已上线</span></div><div><i className="health-building"/><strong>{data.assetHealth.reconstructing}</strong><span>AI重建中</span></div><div><i className="health-review"/><strong>{data.assetHealth.pending_review}</strong><span>待审核</span></div><div><i className="health-failed"/><strong>{data.assetHealth.failed}</strong><span>失败</span></div></div><span className="health-link">查看全部资产 <ArrowRight/></span></Card></section>
    <section className="section-block"><div className="section-title"><h2>快捷操作</h2><span>常用运营入口</span></div><div className="desktop-shortcuts">{shortcuts.map(({ label, caption, icon: Icon, to }) => <button key={label} onClick={() => navigate(to)}><span><Icon/></span><div><strong>{label}</strong><small>{caption}</small></div><ArrowRight/></button>)}</div></section>
  </div>;
}
