import { useMemo, useState } from "react";
import type { Theme } from "@hackday/contracts";
import { ArrowLeft, ArrowRight, Check, Image, X } from "lucide-react";
import { Button } from "../ui";

export interface ThemeEditorResult { theme: Theme; allowVisitorSelection: boolean }
export function ThemeEditorModal({ templates, initial, initiallyAvailable = false, onClose, onSave }: { templates: Theme[]; initial?: Theme; initiallyAvailable?: boolean; onClose: () => void; onSave: (result: ThemeEditorResult) => Promise<void> }) {
  const [step, setStep] = useState(initial ? 2 : 1); const [baseId, setBaseId] = useState(initial?.baseThemeId ?? templates[0].id); const base = templates.find((item) => item.id === baseId) ?? templates[0];
  const [name, setName] = useState(initial?.name ?? ""); const [description, setDescription] = useState(initial?.description ?? ""); const [period, setPeriod] = useState(initial?.environment?.period ?? base.environment?.period ?? "日间"); const [lighting, setLighting] = useState(initial?.environment?.lighting ?? base.environment?.lighting ?? "自然天光"); const [decoration, setDecoration] = useState(initial?.environment?.decoration ?? base.environment?.decoration ?? "轻雾与湖面波光"); const [atmosphere, setAtmosphere] = useState(initial?.tokens.atmosphere ?? base.tokens.atmosphere); const [available, setAvailable] = useState(initiallyAvailable); const [saving, setSaving] = useState(false);
  const canContinue = step === 1 || (step === 2 && name.trim().length >= 2 && description.trim().length >= 4) || step === 3;
  const previewTheme = useMemo<Theme>(() => ({ id: initial?.id ?? "theme-custom-preview", name: name || "新主题", description, sceneIds: base.sceneIds, tokens: { ...base.tokens, atmosphere }, isBuiltIn: false, baseThemeId: base.id, coverKey: `custom-${base.coverKey ?? "theme"}`, environment: { period, lighting, decoration } }), [initial, name, description, base, atmosphere, period, lighting, decoration]);
  const chooseTemplate = (template: Theme) => { setBaseId(template.id); setPeriod(template.environment?.period ?? "日间"); setLighting(template.environment?.lighting ?? "自然天光"); setDecoration(template.environment?.decoration ?? "主题装饰"); setAtmosphere(template.tokens.atmosphere); };
  const submit = async () => { setSaving(true); try { const id = initial?.id ?? `theme-custom-${crypto.randomUUID()}`; await onSave({ theme: { ...previewTheme, id }, allowVisitorSelection: available }); } finally { setSaving(false); } };
  return <div className="modal-backdrop" role="presentation"><section className="theme-editor-modal" role="dialog" aria-modal="true" aria-label={initial ? "编辑自定义主题" : "新建主题"}><header><div><small>主题运营工具</small><h2>{initial ? "编辑自定义主题" : "新建主题"}</h2></div><button onClick={onClose} aria-label="关闭"><X/></button></header><div className="editor-steps">{["选择模板","主题信息","基础效果"].map((label,index)=><div className={index+1<=step?"active":""} key={label}><span>{index+1}</span><small>{label}</small></div>)}</div><div className="editor-content">
    {step===1&&<div className="template-picker"><h3>选择一个基础模板</h3><p>继承成熟的视觉配置，再做少量运营调整。</p><div>{templates.map((template)=><button className={baseId===template.id?"selected":""} key={template.id} onClick={()=>chooseTemplate(template)}><span className={`template-swatch swatch-${template.tokens.atmosphere}`}><Check/></span><strong>{template.name}</strong><small>{template.environment?.period} · {template.environment?.lighting}</small></button>)}</div></div>}
    {step===2&&<div className="editor-form"><div className="cover-placeholder"><Image/><span>主题封面将根据模板生成占位视觉</span></div><label>主题名称<input value={name} onChange={(event)=>setName(event.target.value)} placeholder="例如：七夕夜游"/></label><label>主题简介<textarea rows={3} value={description} onChange={(event)=>setDescription(event.target.value)} placeholder="用一句话说明游客将体验到什么"/></label></div>}
    {step===3&&<div className="editor-form effects-form"><label>环境氛围<select value={atmosphere} onChange={(event)=>setAtmosphere(event.target.value as Theme["tokens"]["atmosphere"])}><option value="mist">湖畔轻雾</option><option value="moonlight">月夜雅集</option><option value="celebration">节庆氛围</option><option value="blossom">春日花海</option></select></label><label>时间段<select value={period} onChange={(event)=>setPeriod(event.target.value)}><option>日间</option><option>黄昏</option><option>暮色 / 夜间</option></select></label><label>灯光类型<input value={lighting} onChange={(event)=>setLighting(event.target.value)}/></label><label>装饰类型<input value={decoration} onChange={(event)=>setDecoration(event.target.value)}/></label><button className="editor-availability" onClick={()=>setAvailable((value)=>!value)}><span className={available?"on":""}><i/></span><div><strong>允许游客选择</strong><small>发布后，游客可在主题入口自主切换</small></div></button></div>}
  </div><footer>{step>1?<Button className="secondary-button" onClick={()=>setStep((value)=>value-1)}><ArrowLeft/>上一步</Button>:<span/>}{step<3?<Button disabled={!canContinue} onClick={()=>setStep((value)=>value+1)}>下一步<ArrowRight/></Button>:<Button disabled={saving} onClick={submit}>{saving?"保存中…":"保存为 Draft"}</Button>}</footer></section></div>;
}
