import { useEffect, useState } from "react";
import { Award, Check, CircleAlert, Gamepad2, Pencil, Save, Sparkles, X } from "lucide-react";
import type { AdminConfigState, MiniGame } from "@hackday/contracts";
import { Button, Card, Loading, StatusBadge } from "../../components/ui";
import { configService } from "../../services/config";
import { useToast } from "../../store/ToastProvider";

const stats: Record<string,{points:string;rate:string}>={"minigame-lantern-riddle":{points:"1,771",rate:"81%"},"minigame-puzzle-restoration":{points:"—",rate:"—"},"minigame-west-lake-treasure":{points:"—",rate:"—"},"minigame-poetry-challenge":{points:"—",rate:"—"}};
export function GamesPage(){const {showToast}=useToast();const [state,setState]=useState<AdminConfigState>();const [editing,setEditing]=useState<MiniGame|null>(null);const [saving,setSaving]=useState(false);useEffect(()=>{configService.getAdminConfig().then(setState);},[]);const save=async(game:MiniGame)=>{setSaving(true);try{const next=await configService.updateDraftMiniGame(game.id,game);setState(next);setEditing(null);showToast("玩法配置已保存为 Draft");}catch(error){showToast(error instanceof Error?error.message:"保存失败","info");}finally{setSaving(false);}};if(!state)return <div className="page"><Loading label="正在读取玩法库"/></div>;return <div className="page games-page"><div className="operations-title"><div><p>杭州西湖景区 · 互动运营</p><h1>玩法库</h1><span>玩法定义“玩什么”，互动点负责投放位置，奖励由玩法或投放点绑定。</span></div><StatusBadge tone="warning">Draft 优先</StatusBadge></div><div className="game-card-grid">{state.draftConfig.miniGames.map(game=>{const reward=state.draftConfig.rewards.find(item=>item.id===game.rewardId);const metric=stats[game.id]??{points:"—",rate:"—"};return <Card className={`game-card ${game.status??"active"}`} key={game.id}><div className="game-cover"><Gamepad2/><span>{game.status==="placeholder"?"未来玩法":"完整 Demo"}</span></div><div className="game-card-body"><div><h2>{game.name}</h2><StatusBadge tone={game.status==="placeholder"?"neutral":"success"}>{game.status==="placeholder"?"占位":"已投放"}</StatusBadge></div><p>{game.description}</p><div className="game-stats"><span>投放人数 <strong>{metric.points}</strong></span><span>完成率 <strong>{metric.rate}</strong></span></div>{reward?<div className="game-reward"><Award/><span>完成奖励：<strong>{reward.name}</strong></span></div>:<div className="game-reward muted"><Sparkles/><span>奖励待后续配置</span></div>}{game.status!=="placeholder"?<Button className="secondary-button" onClick={()=>setEditing(structuredClone(game))}><Pencil size={14}/>编辑玩法</Button>:<Button className="secondary-button" disabled><CircleAlert size={14}/>后续接入</Button>}</div></Card>;})}</div>{editing&&<GameEditor game={editing} rewards={state.draftConfig.rewards} onChange={setEditing} onClose={()=>setEditing(null)} onSave={()=>save(editing)} saving={saving}/>}</div>}
function GameEditor({game,rewards,onChange,onClose,onSave,saving}:{game:MiniGame;rewards:AdminConfigState["draftConfig"]["rewards"];onChange:(game:MiniGame)=>void;onClose:()=>void;onSave:()=>void;saving:boolean}){const riddle=game.riddle??{question:"明月照西湖，打一处西湖十景？",options:["断桥残雪","平湖秋月","雷峰夕照","曲院风荷"],correctOptionIndex:1,successMessage:"答对了！月映断桥纪念卡已收入行囊。",failureMessage:"再想想，答案藏在西湖的月色里。"};const setRiddle=(patch:Partial<typeof riddle>)=>onChange({...game,riddle:{...riddle,...patch}});return <div className="modal-backdrop"><section className="game-editor" role="dialog" aria-label="编辑中秋猜灯谜"><header><div><small>玩法库 · 完整 Demo</small><h2>编辑 {game.name}</h2></div><button onClick={onClose}><X/></button></header><div className="editor-form game-form"><label>玩法简介<textarea rows={2} value={game.description} onChange={event=>onChange({...game,description:event.target.value})}/></label><label>灯谜题目<input value={riddle.question} onChange={event=>setRiddle({question:event.target.value})}/></label><div className="riddle-options"><small>选项与正确答案</small>{riddle.options.map((option,index)=><label key={index}><input type="radio" name="correct" checked={riddle.correctOptionIndex===index} onChange={()=>setRiddle({correctOptionIndex:index})}/><input value={option} onChange={event=>setRiddle({options:riddle.options.map((item,i)=>i===index?event.target.value:item)})}/><span>{riddle.correctOptionIndex===index&&<Check/>}</span></label>)}</div><label>成功文案<input value={riddle.successMessage} onChange={event=>setRiddle({successMessage:event.target.value})}/></label><label>失败文案<input value={riddle.failureMessage} onChange={event=>setRiddle({failureMessage:event.target.value})}/></label><label>完成奖励<select value={game.rewardId??""} onChange={event=>onChange({...game,rewardId:event.target.value||undefined})}>{rewards.map(reward=><option value={reward.id} key={reward.id}>{reward.name}</option>)}</select></label></div><footer><Button className="secondary-button" onClick={onClose}>取消</Button><Button disabled={saving} onClick={onSave}><Save size={15}/>{saving?"保存中…":"保存 Draft"}</Button></footer></section></div>}
