import { useEffect, useState } from "react";
import { Check, CircleDot, Gamepad2, MapPin, Pencil, Save, ToggleLeft, ToggleRight, X } from "lucide-react";
import type { AdminConfigState, InteractionPoint } from "@hackday/contracts";
import { Button, Card, Loading, StatusBadge } from "../../components/ui";
import { configService } from "../../services/config";
import { useToast } from "../../store/ToastProvider";

const typeLabel = { story: "景点故事", mini_game: "玩法触发", teleport: "场景传送" } as const;
const metrics: Record<string, { participants: string; completion: string }> = { "interaction-broken-bridge-story": { participants: "2,767", completion: "82%" }, "interaction-mid-autumn-riddle": { participants: "1,771", completion: "81%" }, "interaction-scene-teleport": { participants: "936", completion: "74%" } };

export function InteractionsPage() {
  const { showToast } = useToast(); const [state,setState]=useState<AdminConfigState>(); const [editing,setEditing]=useState<InteractionPoint|null>(null); const [saving,setSaving]=useState(false);
  const load=()=>configService.getAdminConfig().then(setState);
  useEffect(()=>{load();},[]);
  const toggle=async(point:InteractionPoint)=>{const next=await configService.updateDraftInteraction(point.id,!point.enabled);setState(next);showToast(point.enabled?"互动点已保存为停用 Draft":"互动点已保存为启用 Draft");};
  const save=async(point:InteractionPoint)=>{setSaving(true);try{const next=await configService.updateDraftInteractionDefinition(point.id,point);setState(next);setEditing(null);showToast("互动点配置已保存为 Draft");}catch(error){showToast(error instanceof Error?error.message:"保存失败","info");}finally{setSaving(false);}};
  if(!state)return <div className="page"><Loading label="正在读取互动运营配置"/></div>;
  const scenes=state.draftConfig.scenes;const games=state.draftConfig.miniGames;const rewards=state.draftConfig.rewards;
  return <div className="page interactions-page"><div className="operations-title"><div><p>杭州西湖景区 · 互动运营</p><h1>互动点配置</h1><span>决定游客在哪里触发什么玩法；所有修改仅保存为 Draft。</span></div><StatusBadge tone={state.hasUnpublishedChanges?"warning":"success"}>{state.hasUnpublishedChanges?"有未发布修改":"配置已发布"}</StatusBadge></div>
    <section className="interaction-summary"><Card><small>当前投放点</small><strong>{state.draftConfig.interactionPoints.filter(item=>item.enabled).length}</strong><span>个互动点已启用</span></Card><Card><small>关联玩法</small><strong>{state.draftConfig.miniGames.filter(item=>item.status!=="placeholder").length}</strong><span>个可运营玩法</span></Card><Card><small>奖励投放</small><strong>{state.draftConfig.rewards.length}</strong><span>类数字奖励</span></Card></section>
    <Card className="interaction-explainer"><div><Gamepad2/><span><strong>玩法库：玩什么</strong><small>题目、选项、挑战规则与成功文案</small></span></div><i>→</i><div><MapPin/><span><strong>互动点：在哪里触发</strong><small>场景、热点位置、启停与绑定关系</small></span></div><i>→</i><div><Check/><span><strong>奖励：完成获得什么</strong><small>例如“月映断桥”数字纪念卡</small></span></div></Card>
    <section className="interaction-list">{state.draftConfig.interactionPoints.map(point=>{const scene=scenes.find(item=>item.id===point.sceneId);const game=games.find(item=>item.id===point.miniGameId);const rewardId=point.rewardId ?? game?.rewardId;const reward=rewards.find(item=>item.id===rewardId);const metric=metrics[point.id]??{participants:"—",completion:"—"};return <Card className={`interaction-card ${point.enabled?"enabled":"disabled"}`} key={point.id}><div className="interaction-icon"><CircleDot/></div><div className="interaction-main"><div><h2>{point.name}</h2><StatusBadge tone={point.enabled?"success":"neutral"}>{point.enabled?"已启用":"已停用"}</StatusBadge><StatusBadge tone="neutral">{typeLabel[point.type]}</StatusBadge></div><p><MapPin/> {scene?.name??"未绑定场景"} · {point.position.x}, {point.position.z}</p><div className="interaction-bindings"><span>玩法：<strong>{game?.name??"未绑定"}</strong></span><span>奖励：<strong>{reward?.name??"无"}</strong></span></div></div><div className="interaction-metrics"><small>Mock 参与人数</small><strong>{metric.participants}</strong><small>完成率 <b>{metric.completion}</b></small></div><div className="interaction-actions"><button onClick={()=>toggle(point)} aria-label={point.enabled?"停用互动点":"启用互动点"}>{point.enabled?<ToggleRight/>:<ToggleLeft/>}</button><Button className="secondary-button" onClick={()=>setEditing(structuredClone(point))}><Pencil size={14}/>编辑</Button></div></Card>;})}</section>
    {editing&&<InteractionEditor point={editing} scenes={scenes} games={games} rewards={rewards} onChange={setEditing} onClose={()=>setEditing(null)} onSave={()=>save(editing)} saving={saving}/>}</div>;
}

function InteractionEditor({point,scenes,games,rewards,onChange,onClose,onSave,saving}:{point:InteractionPoint;scenes:AdminConfigState["draftConfig"]["scenes"];games:AdminConfigState["draftConfig"]["miniGames"];rewards:AdminConfigState["draftConfig"]["rewards"];onChange:(point:InteractionPoint)=>void;onClose:()=>void;onSave:()=>void;saving:boolean}){return <div className="modal-backdrop"><section className="interaction-editor" role="dialog" aria-label="编辑互动点"><header><div><small>互动运营</small><h2>编辑 {point.name}</h2></div><button onClick={onClose}><X/></button></header><div className="editor-form interaction-form"><label>互动点名称<input value={point.name} onChange={event=>onChange({...point,name:event.target.value})}/></label><label>绑定场景<select value={point.sceneId} onChange={event=>onChange({...point,sceneId:event.target.value})}>{scenes.map(scene=><option value={scene.id} key={scene.id}>{scene.name}</option>)}</select></label><label>互动类型<select value={point.type} onChange={event=>onChange({...point,type:event.target.value as InteractionPoint["type"]})}><option value="story">景点故事</option><option value="mini_game">玩法触发</option><option value="teleport">场景传送</option></select></label><label>绑定玩法<select value={point.miniGameId??""} onChange={event=>onChange({...point,miniGameId:event.target.value||undefined})}><option value="">未绑定</option>{games.map(game=><option value={game.id} key={game.id}>{game.name}</option>)}</select></label><label>绑定奖励<select value={point.rewardId??""} onChange={event=>onChange({...point,rewardId:event.target.value||undefined})}><option value="">跟随玩法奖励 / 无</option>{rewards.map(reward=><option value={reward.id} key={reward.id}>{reward.name}</option>)}</select></label><label>投放位置 X<input type="number" value={point.position.x} onChange={event=>onChange({...point,position:{...point.position,x:Number(event.target.value)}})}/></label><label>投放位置 Z<input type="number" value={point.position.z} onChange={event=>onChange({...point,position:{...point.position,z:Number(event.target.value)}})}/></label></div><footer><Button className="secondary-button" onClick={onClose}>取消</Button><Button disabled={saving} onClick={onSave}><Save size={15}/>{saving?"保存中…":"保存 Draft"}</Button></footer></section></div>}
